School: 成都理工大学
Timestamp: 20250509_234139
Error Message: 获取页面失败 (url: https://gra.cdut.edu.cn/): 412 Client Error: Precondition Failed for url: https://gra.cdut.edu.cn/

Exception Type: HTTPError
Exception Details: 412 Client Error: Precondition Failed for url: https://gra.cdut.edu.cn/

Traceback:
Traceback (most recent call last):
  File "/Users/mac/WorkSpace/考研推荐系统/utils/scraper.py", line 271, in fetch_page
    response.raise_for_status() # 如果请求失败 (4xx, 5xx) 则抛出异常
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/mac/WorkSpace/考研推荐系统/.venv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 412 Client Error: Precondition Failed for url: https://gra.cdut.edu.cn/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mac/WorkSpace/考研推荐系统/utils/scraper.py", line 271, in fetch_page
    response.raise_for_status() # 如果请求失败 (4xx, 5xx) 则抛出异常
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/mac/WorkSpace/考研推荐系统/.venv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 412 Client Error: Precondition Failed for url: https://gra.cdut.edu.cn/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mac/WorkSpace/考研推荐系统/utils/scraper.py", line 271, in fetch_page
    response.raise_for_status() # 如果请求失败 (4xx, 5xx) 则抛出异常
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/mac/WorkSpace/考研推荐系统/.venv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 412 Client Error: Precondition Failed for url: https://gra.cdut.edu.cn/
